Add tests for book and category entity
yulka-tsybulka/book_market pull request #2
Opened 2024-04-24 17:20 UTC by yulka-tsybulka

2024-04-24 17:22 UTC, yulka-tsybulka commented
![Tests coverage](https://github.com/yulka-tsybulka/book_market/assets/99347197/eb170fdd-478c-49d6-a526-6585abefc8e5)

2024-04-24 18:25 UTC, kerrrusha requested changes

2024-04-24 18:25 UTC, kerrrusha commented on src/test/java/my/book/market/config/CustomMySqlContainer.java
> +    }
changes nothing
```suggestion
```

2024-04-24 18:25 UTC, kerrrusha commented on src/test/java/my/book/market/controller/CategoryControllerTest.java
> +public class CategoryControllerTest {
add negative tests

2024-04-24 18:25 UTC, kerrrusha commented on src/test/java/my/book/market/controller/BookControllerTest.java
> +class BookControllerTest {
add negative tests

2024-04-25 12:51 UTC, kerrrusha approved these changes

2024-04-25 12:52 UTC, merged